### PR TITLE
All Unicode characters.

### PR DESCRIPTION
**Pull request by elbachir-one**
Update the Makefile to add -D_GNU_SOURCE  to enable GNU-specific features.
Adding support for all Unicode characters.
Here is some videos:
https://streamable.com/s9etds
https://streamable.com/7ie7iu

### CODE REVIEW

**Comment by cdkw2** [comment]
wait, I think I did merge this... Maybe I just forgot I'll do it again.

**Comment by elbachir-one** [comment]
You didn't merge it before.

**Comment by cdkw2** [comment]
> You didn't merge it before.

And I am gonna have to revert it because I think I have found a bug!

**Comment by cdkw2** [comment]
@elbachir-one  Ok, so I saw you wrote some of the main code and decided to get a side by side look at my old version and your new unicode version, first of all I thank you a lot of taking your precious time in helping me out. So I saw that your code is not spawning gliders properly in set intervals, I have get a video for you too, you see how in my version (the right side) after a while a glider collides with a equilibrium and breaks it, the grid is larger so it is les probable but it is there. But in your version I see that after like waiting like a solid 2 minutes I dont see any gliders changing the grid, you can see the comparison in the video itself. Please look into it if you can because I am like busy because of exams lol. Anyway I intentionally sped them up so the you can see that even after a long time no gliders collide and its not jjust bad luck with the probabilities. 


https://github.com/user-attachments/assets/5238f1ee-8769-4fe0-830e-7a7284a1cb71

**Pull request merged**
