### PR TITLE
Adding the Makefile and update the readme

### PR DESCRIPTION
**Pull request by elbachir-one**
Added the Makefile and updated the README.

### CODE REVIEW

**Comment by cdkw2** [comment]
I think I am having some issues with the make file

image

And I dont understand make file like at all so I dont know what to do.

**Comment by elbachir-one** [comment]
image

That's fine—those are just normal warnings from the CFLAGS, and I can turn them off if you want. If there were any issues, an error would be displayed, and Conway wouldn't be built. However, that's not the case here, so if you check, you'll see that Conway was built successfully. The Makefile is meant to simplify the build process instead of doing it manually. Also, I noticed that you used 'chmod +x conway'; it's not a script, so there's no need to do that.

CFLAGS = -Wall -Wextra -pedantic -std=c99

-Wall: Enables most common warning messages during compilation. This helps catch potential issues in the code.
-Wextra: Enables additional warning messages that are not included with -Wall. These warnings are more specific and can help identify even more potential issues.
-pedantic: Enforces strict adherence to the C standard (in this case, C99). It generates warnings for any code that is not strictly compliant with the standard.
-std=c99: Specifies that the code should be compiled according to the C99 standard, which is a version of the C programming language standard published in 1999.

**Comment by cdkw2** [comment]
> image
> 
> That's fine—those are just normal warnings from the CFLAGS, and I can turn them off if you want. If there were any issues, an error would be displayed, and Conway wouldn't be built. However, that's not the case here, so if you check, you'll see that Conway was built successfully. The Makefile is meant to simplify the build process instead of doing it manually. Also, I noticed that you used 'chmod +x conway'; it's not a script, so there's no need to do that.
> 
> CFLAGS = -Wall -Wextra -pedantic -std=c99
> 
> -Wall: Enables most common warning messages during compilation. This helps catch potential issues in the code. -Wextra: Enables additional warning messages that are not included with -Wall. These warnings are more specific and can help identify even more potential issues. -pedantic: Enforces strict adherence to the C standard (in this case, C99). It generates warnings for any code that is not strictly compliant with the standard. -std=c99: Specifies that the code should be compiled according to the C99 standard, which is a version of the C programming language standard published in 1999.

Hmmmm, I get it but the output on your screen is different from mine, I get 

make: *** [Makefile:15: conway.o] Error 1

and the conway file is not generated.

**Comment by elbachir-one** [comment]
Oh, now I understand what's happening. I'm using Void Linux with GCC version 13.2.0, while you are using Arch Linux (EndeavourOS) with GCC version 14.1.1. I will update the Makefile accordingly.

Note: The Makefile is up to date.

**Comment by cdkw2** [comment]
Sure I'll add it!

**Comment by cdkw2** [comment]
> Oh, now I understand what's happening. I'm using Void Linux with GCC version 13.2.0, while you are using Arch Linux (EndeavourOS) with GCC version 14.1.1. I will update the Makefile accordingly.
> 
> Note: The Makefile is up to date.

Thanks for the contribution!

**Pull request merged**
